wdn_names: # support loading multiple networks 
- CTOWN_1GB_24H
node_attrs:
- pressure
-   
  - reservoir_base_head
  - junction_elevation
  - tank_elevation
edge_attrs:
- pipe_length
- pipe_diameter
label_attrs: 
- demand
edge_label_attrs: [] #keep it empty if unused
num_records: 100 #this number will be divided into 60%train-20%val-20%test
batch_axis_choice: scene # unit of records
selected_snapshots: null
verbose: false # turn on for more debug info
split_type: scene # two way to split data - scenario or temporal axis
split_set: all  # take subset only. 4 options: train/val/test and all
skip_nodes_list: [] # put the name of node here to skip. By default, we ADDED skip nodes w.r.t. the generation config.
skip_types_list: [] # faster way to ignore component type (e.g., reservour, tank).
unstackable_pad_value: -1.0
bypass_skip_names_in_config: false
do_lazy: false
overwatch: false
do_cache: false # set True if your RAM can handle the whole array.
subset_shuffle: false  # if True, we shuffle the subset and STORE the shuffle ids. Otherwise, we do sampling with a dedicated step size w.r.t. num_records.              
split_per_network: true # Assume we choose num_records 10_000, so #samples of training subset is 6_000. If you have 2 networks, we will sample 3_000 per each.
